### ISSUE TITLE
Get pollution data / From location - Title Suggestion

### ISSUE THREAD

**Issue by kwmc-lucas** [Kevjolly/AirPollutionDataPlatform#13]
The button on the homepage and the 'Get pollution data' drop-down menu item could be 'Search A Location'

**Comment by bitvijays** [comment]
@kwmc-lucas Do we have any other suggestion than `Search A Location` ? 

- Search a location doesn't kind of tell that we are looking for pollution data.
- If we keep it as `Search a location`, 
![image](https://user-images.githubusercontent.com/9039339/99605291-4f5fa680-29ff-11eb-86c2-54a1991a0843.png)
 It would be like 

Search a location
- From location
- View all sensors

^ location twice doesn't make sense.
